Bash:
  - "(Bash|bash|BASH)"
Golang:
  - "(Go|GO|Golang|GOLANG)"
JavaScript:
  - "(JavaScript|JAVASCRIPT|Javascript|javascript|JS|js)"
Python:
  - "(Python|PYTHON|python)"
enhancement:
  - "(enhancement)"
CH20:
  - "(CH20)"
Easy:
  - "(Easy|easy|EASY)"  
Medium:
  - "(Medium|medium|MEDIUM)"
Hard:
  - "(Hard|hard|HARD)"
Up-for-grab:
  - "(up for grab)"
