Bash:
  - "(Bash|bash)"
Golang:
  - "(Go|GO|Golang)"
JavaScript:
  - "(JavaScript|JAVASCRIPT|Javascript|javascript|JS|js)"
Python:
  - "(Python|PYTHON|python)"
enhancement:
  - "(enhancement)"
CH20:
  - "(CH20)"
Easy:
  - "(Easy|easy)"  
Medium:
  - "(Medium|medium)"
Hard:
  - "(Hard|hard)"
  