name: Greet

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: TylerLeonhardt/first-interaction-pwsh@v0.1.0

      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi @${{github.actor}} thanks fo creating an issue I hope you have read the contribution guidelines'
        pr-message: 'Hi thanks for submitting the PR I hope you have read the clean code guidelines.'
